/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package policlinica;

import javafx.application.Application;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import policlinica.controllers.AngajatiListController;
import policlinica.controllers.LogInController;
import policlinica.controllers.MainController;
import policlinica.controllers.UserController;

public class App extends Application {

	private Stage window;

	private LogInController logInController;
	private MainController mainController;

	public static void main(String[] args) {
		launch(args);
    }

	@Override
	public void start(Stage primaryStage) throws Exception {
		window = primaryStage;

		FXMLLoader loader = new FXMLLoader(getClass().getResource("/logInLayout.fxml"));
		Parent logInLayout = loader.load();
		logInController = loader.getController();

		loader = new FXMLLoader(getClass().getResource("/mainLayout.fxml"));
		Parent mainLayout = loader.load();
		mainController = loader.getController();

		Scene logInScene = new Scene(logInLayout, 800, 600);
		logInScene.getStylesheets().add("logInStyle.css");

		Scene mainScene = new Scene(mainLayout, 800, 600);
		mainScene.getStylesheets().add("mainStyle.css");

		mainController.setLogInController(logInController);
		mainController.setLogInScene(logInScene);
		mainController.subLayoutLoading();

		logInController.setMainController(mainController);
		logInController.setMainScene(mainScene);


		primaryStage.minWidthProperty().setValue(700);
		primaryStage.minHeightProperty().setValue(500);
		window.setTitle("Administrare Policlinica");
		window.setScene(logInScene);
		window.show();
	}

}
